before_script:
 - apt-get update -qq && 
 
r305library:
 script:
  make r305Parser

test_exe:
 script:
  - apt-get install -y -qq mingw32 mingw-w64
  - make test_exe_ci
 artifacts:
   untracked: true

test_avr:
 script:
  - apt-get install -y -qq avr-libc gcc-avr binutils-avr 
  - make test_avr
 artifacts:
   untracked: true

doc:
 script:
  - apt-get install -y -qq doxygen 
  - make doc
 