before_script:
 - apt-get update -qq && apt-get install -y -qq build-essential doxygen avr-libc gcc-avr binutils-avr

 
r305library:
 script:
  make r305Parser

test_exe:
 script:
  make test_exe

test_avr:
 script:
  make test_avr
 artifacts:
   untracked: true
   path:
   - binaries/

doc:
 script:
  make doc
